---
title: "TC summary statistics for use in CLIMADA"
author: "Melissa Renard"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, warning=FALSE, include=FALSE}
rm(list = ls())

# ChatGPT used for the below code: required packages
# Define a list of required packages
required_packages <- c("tidyverse", "markovchain")

# Check if the packages are installed, and if not, install them
for (pkg in required_packages) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
}

# Load the packages into the session
invisible(lapply(required_packages, library, character.only = TRUE))

knitr::opts_chunk$set(echo = TRUE) 
```

```{r import-data}
tracks <- read.csv('Data/tracks.csv', na = '')

tracks <- tracks %>% rename('t_day' = 'days_since_1980', 
                  't_year' = 'years_since_1980', 
                  'Nt' = 'TC_num') %>%
  mutate(category = as.factor(category),
         t_month = lapply(t_year, function(x) x*12) %>% unlist,
         east170 = ifelse(basin == 'SP', lon > 170, NA),
         east75 = ifelse(basin %in% c('SI', 'NI'), lon > 75, NA),
         east244 = ifelse(basin=='EP', lon > 244, NA),
         north20 = ifelse(basin=='NA', lat > 20, NA),
         north16 = ifelse(basin=='WP', lat > 16, NA),
         east134 = ifelse(basin== 'WP', lon > 134, NA),
         range_sw = max_sw - min_sw,
         Nt = as.integer(rownames(tracks)))

tracks_1 <- tracks %>% 
  mutate(enso_year = ifelse(basin %in% c('SI', 'SP'), 
                            year + (month > 7), year)) %>% 
  filter(
    (
    (basin %in% c('SI','SP') & enso_year >= 1981) |
    (basin %in% c('NA', 'WP') & enso_year >= 1980) |
    (basin == 'NI' & enso_year >= 1990) | 
    (basin == 'EP' & enso_year >= 1988)
    ) & enso_year <= 2023 
  )

# Load ENSO data
enso_df <- read.csv('Data/ENSO.csv', skip = 3, header = TRUE)

tracks_1 <- tracks_1 %>% left_join(enso_df, by = join_by(enso_year==year))

basins <- tracks_1 %>% distinct(basin) %>% pull %>% sort
enso_phases <- c('Nina', 'Neutral', 'Nino')
```

# ENSO Markov Chain

```{r enso-mc}
enso_mc <- markovchainFit(enso_df$enso[enso_df$year <= 2023], 
                          possibleStates = enso_phases,
                          method = "mle")

my_MC <- enso_mc$estimate@transitionMatrix[enso_phases, enso_phases]

my_MC %>% write.csv("R tables/enso_MC.csv")
```


# Number of tracks, CLIMADA

Number of tracks in each basin between January 1980 and December 2023, CLIMADA.

```{r n-tracks-climada}
n_tracks_CLIMADA <- tracks %>%
  # number of tracks by basin
  count(basin) %>% 
  # transpose table
  pivot_wider(names_from = basin, values_from = n) %>% 
  # remove SA basin which is not of interest
  select(-'SA') 

n_tracks_CLIMADA %>% write.csv('R tables/n_tracks_CLIMADA.csv', row.names = FALSE)
```


# MMNHPP
```{r mmnhpp}
# Number of ENSO years in each basin for the observation periods. 
# Each row is ENSO phase
# Each column is a basin
n_enso_basin <- enso_df %>% 
  # NA and WP basins
  filter(year >= 1980 & year < 2024) %>% count(enso, name = 'NA') %>%
  # SI and SP basins
  left_join(enso_df %>% filter(year >= 1981 & year < 2024) %>% 
              count(enso, name = 'SI'), by=join_by(enso)) %>%
  # EP basin
  left_join(enso_df %>% filter(year >= 1988 & year < 2024) %>% 
              count(enso, name = 'EP'), by=join_by(enso)) %>%
  # NI basin
  left_join(enso_df %>% filter(year >= 1990 & year < 2024) %>% 
              count(enso, name = 'NI'), by=join_by(enso)) %>%
  # add WP and SP basins
  mutate(WP= `NA`, SP = SI) %>%
  # sort basin columns alphabetically
  select(1, sort(names(.))) %>% 
  # order rows by Nina, Neutral, Nino
  mutate(enso = factor(enso, levels = enso_phases)) %>% 
  arrange(enso) %>%
  mutate(enso = as.character(enso))

# setup for parameter estimating

# Widen n_enso_basin to one row
n_enso_basin_wider <- n_enso_basin %>% 
  pivot_longer(-1, names_to = 'basin') %>% 
  pivot_wider(names_from = c(basin, enso), values_from = value) %>% 
  select(sort(names(.)))

# total observed number of tracks each month, split by basin and ENSO phase
obs_tracks <- tracks_1 %>% 
  group_by(basin, enso, month) %>%
  # number of tracks
  summarise(n_tracks = n()) %>%
  # fill out months with 0 observations
  complete(month = 1:12, fill = list(n_tracks = 0)) %>%
  # widen table by basin and ENSO phase
  pivot_wider(names_from = c(basin, enso), values_from = n_tracks) 

# standardised obs_tracks to be annual -- 'lambda'
# divide obs_tracks in each phase and basin by the number of years observed
# in each phase and basin (each basin has a different observation period), 
# to get the average monthly number of tracks by basin and ENSO phase.
# multiply by 12 to standardise to yearly values.
obs_lambda <- t(t(obs_tracks[-1]) / as.numeric(n_enso_basin_wider) * 12) %>% 
  as.tibble %>%
  # time where the unit is years
  mutate(time = 1:12/12) %>% select(time, sort(names(.))) %>%
  
  # pivot table longer so each column is a basin
  pivot_longer(cols = 2:19, names_to = c("basin", "enso"), names_sep = "_", 
               values_to = "n_tracks") %>%
  pivot_wider(names_from = basin, values_from = n_tracks) %>%
  
  # order rows by Nina, Neutral, Nino
  mutate(enso = factor(enso, levels = enso_phases)) %>% 
  arrange(enso) %>%
  mutate(enso = as.character(enso))
```

```{r mmnhpp-par}
# empty table for inputting the hyperparameters
MMNHPP_par <- tibble(
  enso = c(rep('Nina', 4), rep('Neutral', 4), rep('Nino', 4)),
  param = rep(c('a','b','c','d'), 3)
)

# seasonal function: fitting the hyperparameters
seasonal_fn <- function(t, params){
  return(params[1] + params[2]*exp(params[3]*sin(2*pi*t + params[4]))) 
  # Note that we have 2*pi*t because seasonality is yearly.
}

# Obtain the hyperparameters for the NHPPs under each basin and ENSO phase
# Use least square method with seasonal_fn
for (basin in basins){
  my_params_basin <- NULL
  for (phase in enso_phases){
    # function to minimise: SS
    SS <- function(params, 
                   t = obs_lambda$time[1:12], 
                   y = obs_lambda %>% filter(enso == phase) %>% 
                     select(basin) %>% pull){
      return( sum((seasonal_fn(t, params) - y)^2) )
    }
    my_optim <- optim(par = c(1,1,1,1), fn = SS)
    my_params <- my_optim$par
    my_params_basin <- c(my_params_basin, my_params)
  }
  MMNHPP_par <- MMNHPP_par %>% cbind(my_params_basin)
}

colnames(MMNHPP_par) <- c('enso', 'params', basins)

MMNHPP_par %>% write.csv('R tables/MMNHPP_par.csv', row.names = FALSE)
```

# Severity by ENSO

```{r severity-enso}
severity_enso <- tracks_1 %>%
  group_by(basin, enso) %>%
  summarise(avg_severity = mean(max_sw)) %>%  pivot_wider(names_from = basin, values_from = avg_severity) %>% 
  # order rows by Nina, Neutral, Nino
  mutate(enso = factor(enso, levels = enso_phases)) %>% 
  arrange(enso) %>%
  mutate(enso = as.character(enso))

severity_enso %>% select(-enso) %>% 
  write.csv('R tables/severity_enso.csv', row.names = FALSE)
```





